---
issues:
  exclude-rules:
    - linters: [forbidigo]
      path: cmd/
      text: use of `fmt\.Print(ln|f)?` forbidden by pattern
    - linters: [stylecheck]
      path: _test\.go
      source: "`.*ß.*`"
      text: "ST1018" # we want unicode control chars in there.
    - linters: [exhaustivestruct]
      path: _test\.go
    - linters: [goerr113]
      path: pwgen/genpw_test\.go
    - linters: [testpackage]
      path: cmd/
    - linters: [goerr113]
      path: pwgen/buildcharsets_test\.go
      # allow very long strings to surpass max line length unbroken
      # if they get their own line
    - linters: [lll]
      source: '^\s*(\[\]rune\()?"......................*"(\))?,?$'
    - linters: [gochecknoglobals]
      # this package is suppopsed to export global vars
      path: charsets/defaults\.go
      source: '^var DefaultCharsets'
    - linters: [revive]
      text:
        '(add-constant: (avoid magic numbers like|string literal "")|cyclomatic: function parseOpts|deep-exit: calls to log\.Panicf? only in main)'
    - linters: [revive]
      path: _test\.go
      # tests can have magic vals and up to 5 function args
      text: '^(add-constant: |argument-limit: maximum number of arguments per function exceeded; max 4 but got 5)'
      # parseOpts length is soley determined by cli flag count.
    - linters: [funlen, cyclop]
      path: cmd/
      source: 'func parseOpts'
  exclude-use-default: false
  max-issues-per-linter: 0
linters:
  disable-all: true
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - cyclop
    - deadcode
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - exhaustivestruct
    - exportloopref
    - forbidigo
    - forcetypeassert
    - funlen
    - gci
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - goerr113
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomnd
    - gomoddirectives
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ifshort
    - importas
    - ineffassign
    - ireturn
    - lll
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - promlinter
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - structcheck
    - stylecheck
    - tagliatelle
    - testpackage
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - wastedassign
    - whitespace
    - wrapcheck
    - wsl
    # - varnamelen # not always applicable
    # - gomodguard # obsoleted by go-arch-lint
    # - paralleltest # not always relevant
    # - tenv # only for go117+; I'll require go117+ when go119 is out.
    # - scopelint # deprecated
    # - maligned # deprecated
    # - golint # deprecated
    # - interfacer # deprecated
linters-settings:
  cyclop:
    max-complexity: 9
    package-average: 5
  unparam:
    check-exported: true
  dupl:
    threshold: 40
  errcheck:
    check-blank: true
    check-type-assertions: true
  goconst:
    numbers: true
  staticcheck:
    checks: ["all"]
    initialisms: []
  stylecheck:
    checks: ["all"]
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
      - experimental
      - opinionated
    disabled-checks:
      - ioutilDeprecated # moac should work in Go 1.15+
    settings:
      captLocal:
        paramsOnly: false
      elseif:
        skipBalanced: false
      hugeParam:
        sizeThreshold: 64
      rangeExprCopy:
        sizeThreshold: 128
        skipTestFuncs: false
      rangeValCopy:
        sizeThreshold: 96
        skipTestFuncs: false
      nestingReduce:
        bodyWidth: 3
      truncateCmp:
        skipArchDependent: false
  gomnd:
    settings:
      mnd:
        ignored-numbers:
          - 2
          - 10
          - 32
          - 64
  govet:
    check-shadowing: true
    enable-all: true
  misspell:
    locale: US
  nestif:
    min-complexity: 3
  nolintlint:
    allow-leading-space: false
    allow-unused: false
    require-explanation: true
    require-specific: true
  prealloc:
    for-loops: true
    simple: false
  predeclared:
    q: true
  funlen:
    lines: 80
    statements: 25
  revive:
    confidence: 0.21
    rules:
      - name: add-constant
      - name: argument-limit
        arguments: [4]
      - name: atomic
      - name: bare-return
      - name: blank-imports
      - name: bool-literal-in-expr
      - name: call-to-gc
      - name: cognitive-complexity
        arguments: [10]
      - name: confusing-naming
      - name: confusing-results
      - name: constant-logical-expr
      - name: context-as-argument
      - name: context-keys-type
      # - name: cyclomatic # redundant with the cyclomatic linter
      - name: deep-exit
      - name: defer
      - name: dot-imports
      - name: duplicated-imports
      - name: early-return
      - name: empty-block
      - name: empty-lines
      - name: error-naming
      - name: error-return
      - name: error-strings
      - name: errorf
      - name: exported
      # - name: file-header
      - name: flag-parameter
      - name: function-result-limit
        arguments: [4]
      # - name: function-length # redundant by funlen
      - name: get-return
      - name: identical-branches
      - name: if-return
      - name: import-shadowing
      - name: imports-blacklist
        arguments: ["math/rand"]
      - name: increment-decrement
      - name: indent-error-flow
      # - name: line-length-limit # redundant by lll
      - name: max-public-structs
        arguments: [3]
      - name: modifies-parameter
      - name: modifies-value-receiver
      - name: nested-structs
      - name: package-comments
      - name: range
      - name: range-val-in-closure
      - name: receiver-naming
      - name: redefines-builtin-id
      - name: string-of-int
      # - name: string-format
      - name: struct-tag
      - name: superfluous-else
      - name: time-naming
      - name: unconditional-recursion
      - name: var-declaration
      - name: var-naming
      - name: unexported-naming
      - name: unexported-return
      - name: unhandled-error
        arguments:
          - fmt.Printf
          - fmt.Print
          - fmt.Println
          - fmt.Fprintf
          - fmt.Fprint
          - password.WriteRune
          - filteredCharset.WriteRune
          - ccBuilder.WriteString
          - warningSubstring.WriteString
      - name: unnecessary-stmt
      - name: unreachable-code
      - name: unused-parameter
      - name: unused-receiver
      - name: useless-break
      - name: waitgroup-by-value
  gosec:
    config:
      global:
        audit: enabled
  wsl:
    force-case-trailing-whitespace: 2
    # force-short-decl-cuddling: true
run:
  deadline: 1m
  skip-dirs-use-default: true
  modules-download-mode: readonly
  skip-files: []

output:
  sort-results: true
